site_name: krixik docs
nav:
  - Home: index.md
  - Pipeline examples:
    - 'overview': examples/overview.md
    - transcribe examples:
      - 'semantically searchable transcription': examples/transcribe/transcribe-semantic.md
      - 'keyword searchable transcription': examples/transcribe/transcribe-keyword.md
      - 'multilingual transcription': examples/transcribe/transcribe-multilingual.md
      - 'semantically searchable multilingual transcription': examples/transcribe/transcribe-multilingual-semantic.md
      - 'transcribe to sentiment analysis': examples/transcribe/transcribe-sentiment.md
    - summarize examples:
      - 'recursive summarization': examples/summarize/recursive_summarize.md
    - text search:
      - 'keyword search': examples/text-search/keyword_search.md
      - 'semantic search': examples/text-search/semantic_search.md
  - Modules:
    - 'overview': modules/overview.md
    - currently available:
      - 'caption': modules/caption.md
      - 'json-to-txt': modules/json-to-txt.md
      - 'keyword-db': modules/keyword-db.md
      - 'ocr': modules/ocr.md
      - 'parser': modules/parser.md
      - 'sentiment': modules/sentiment.md
      - 'summarize': modules/summarize.md
      - 'text-embedder': modules/text-embedder.md
      - 'transcribe': modules/transcribe.md
      - 'translate': modules/translate.md
      - 'vector-db': modules/vector-db.md
  - System:
    - 'overview': system/overview.md
    - methods:
      - 'install cli': system/install.md
      - 'initialize': system/initialize.md
      - 'convenience methods': system/convenience_methods.md
      - 'create, save, and load pipelines': system/create_save_load.md
      - 'the process method': system/process.md
      - 'the process_status method': system/process_status.md
      - 'the fetch_output method': system/fetch_output.md
      - 'the list method': system/list.md
      - 'the update method': system/update.md
      - 'the delete method': system/delete.md
      - 'the show_tree method': system/show_tree.md
      - 'the keyword_search method': system/keyword_search.md
      - 'the semantic_search method': system/semantic_search.md
theme: 
  name: readthedocs
plugins:
  - mkdocstrings:
      default_handler: python
  - search
  # - section-index
