# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" , "sta"]
    paths-ignore:
      - '**/README.md'
      - '**/CONTRIBUTING.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/CONTRIBUTING.md'

jobs:
  ruff:
    name: lint with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
          config: .ruff.toml
  test:
    name: run pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.in
    - name: Run pytest
      run: |
        PYTHONPATH=. python3.10 -m pytest tests/test_1_conversion_no_remove.py &&
        PYTHONPATH=. python3.10 -m pytest tests/test_2_toc_file_check.py &&
        PYTHONPATH=. python3.10 -m pytest tests/test_4_links.py &&
        PYTHONPATH=. python3.10 -m pytest tests/test_5_names.py &&
        PYTHONPATH=. python3.10 -m pytest tests/test_6_data.py &&
        PYTHONPATH=. python3.10 -m pytest tests/test_7_reset.py &&
        PYTHONPATH=. python3.10 -m pytest tests/test_9_conversion_remove.py
